-- Add teaching_extra column (introduction, song, think_about_it, confession, closing_prayer, video_description)
ALTER TABLE lessons ADD COLUMN teaching_extra TEXT NOT NULL DEFAULT '{}';

-- ─────────────────────────────────────────────────
-- WEEK 1 — Blessed to Be a Blessing
-- ─────────────────────────────────────────────────
UPDATE lessons SET teaching_extra = '{"introduction":"God blesses us so we can bless others. When we share, we show God''s love.","activity_note":"See activity page.","confession":"I will be a blessing to others.","closing_prayer":"Help me to share and be a blessing every day.","think_about_it":"What is one thing you can share with someone today?","video_description":"Watch the video to learn how God wants us to be a blessing to others.","song":{"title":"I Am Blessed","lyrics":"I am blessed, yes I am,\nI can share with everyone!\nGod has blessed me, yes He has,\nSo I can bless others too!\n(Clap, clap!)","actions":["Clap your hands.","Share with a friend.","Thank God for your blessings."]}}' WHERE id = 'lesson-w1-age-0-4';

UPDATE lessons SET teaching_extra = '{"introduction":"God blesses us with a purpose — to bless others. A cheerful giver shows God''s heart.","activity_note":"See activity page.","confession":"I will share my blessings with others.","closing_prayer":"Lord, help me to give cheerfully and be a blessing this week.","think_about_it":"1. How has God blessed you this week?\n2. Who can you be a blessing to?\n3. What makes giving feel good?","video_description":"Watch the video to discover how we can be a blessing to those around us."}' WHERE id = 'lesson-w1-age-5-9';

UPDATE lessons SET teaching_extra = '{"introduction":"Being a blessing is not just about money — it is about using everything God has given you to serve others.","activity_note":"See activity page.","confession":"I commit to using my gifts to bless others.","closing_prayer":"Father, show me how to use what You have given me to make a difference for someone this week.","think_about_it":"1. What gifts or talents has God given you?\n2. How can you use them to bless others?\n3. What does it mean to be a channel of God''s blessing?","video_description":"Watch the video to explore how God calls us to live as blessings in the world."}' WHERE id = 'lesson-w1-age-10-12';

UPDATE lessons SET teaching_extra = '{"introduction":"God''s economy works differently from the world''s — generosity multiplies rather than diminishes. You are blessed to be a blessing.","activity_note":"See activity page.","confession":"I choose to live as a blessing, not just a receiver.","closing_prayer":"Father, break the spirit of selfishness in me. Make me a generous person who reflects Your heart to this generation.","think_about_it":"1. In what areas are you holding back from being generous?\n2. What would it look like to truly live as someone blessed to be a blessing?\n3. How does generosity reflect God''s character?","video_description":"Watch the video to understand the Kingdom principle of being blessed to be a blessing."}' WHERE id = 'lesson-w1-age-13-19';

-- ─────────────────────────────────────────────────
-- WEEK 2 — Obedience Pleases God
-- ─────────────────────────────────────────────────
UPDATE lessons SET teaching_extra = '{"introduction":"God is happy when I listen. Obeying shows I love God.","activity_note":"See activity page.","confession":"I obey God.","closing_prayer":"Help me to obey always.","think_about_it":"What is one thing you can obey today?","video_description":"Watch the video to learn that God wants me to obey.","song":{"title":"I Will Obey","lyrics":"I will obey, I will obey,\nGod is happy when I obey!\nI will obey, I will obey,\nGod is happy when I obey!\n(Clap, clap!)","actions":["👏 Clap your hands.","❤️ Love God.","😊 Obey every day."]}}' WHERE id = 'lesson-w2-age-0-4';

UPDATE lessons SET teaching_extra = '{"introduction":"Obeying shows love and respect. God wants us to obey in love, not just because we have to.","activity_note":"See activity page.","confession":"I choose to obey always.","closing_prayer":"Dear God, help me to obey quickly and with a happy heart. In Jesus'' name, Amen.","think_about_it":"1. Why is obedience important?\n2. What happens when we obey?\n3. Who can help us to obey?","video_description":"Watch the video to learn why obedience pleases God."}' WHERE id = 'lesson-w2-age-5-9';

UPDATE lessons SET teaching_extra = '{"introduction":"Obedience requires choice. God sees obedience as a matter of the heart, not just outward behaviour. Character shapes destiny.","activity_note":"See activity page.","confession":"I choose to obey God even when it is hard.","closing_prayer":"Dear God, help me to obey You in every situation. I want to honour You with my choices. In Jesus'' name, Amen.","think_about_it":"1. What is God asking you to obey right now?\n2. What will you do if it is hard to obey?\n3. How does obedience show that we love God?","video_description":"Watch the video to understand how obedience shapes your character and future."}' WHERE id = 'lesson-w2-age-10-12';

UPDATE lessons SET teaching_extra = '{"introduction":"Obedience requires character. Every decision to obey or disobey is shaping who you are becoming. Choose wisely.","activity_note":"See activity page.","confession":"I will choose obedience even when no one is watching.","closing_prayer":"Heavenly Father, I want to choose obedience even when it costs me. I commit my decisions to You. In Jesus'' name, Amen.","think_about_it":"1. Why is it important to obey God even when no one is watching?\n2. How does disobedience affect your future?\n3. What will you choose when it is not easy?","video_description":"Watch this video to understand how obedience affects your future and reflects your faith."}' WHERE id = 'lesson-w2-age-13-19';

-- ─────────────────────────────────────────────────
-- WEEK 3 — God's Power Helps Us
-- ─────────────────────────────────────────────────
UPDATE lessons SET teaching_extra = '{"introduction":"God is always with me. When I feel scared, God gives me strength and power.","activity_note":"See activity page.","confession":"God''s power helps me every day.","closing_prayer":"Dear God, thank You that You are always with me. Help me to remember Your power when I feel scared. In Jesus'' name, Amen.","think_about_it":"When do you need God''s strength the most?","video_description":"Watch the video and learn how God gives us strength to do hard things.","song":{"title":"God Is With Me","lyrics":"God is with me, yes He is!\nHe gives me strength, I can do it!\nGod is with me,\nI can trust Him always!\n(Clap, clap!)","actions":["🙌 Raise your hands to God.","💪 Flex your arms — God makes you strong!","❤️ God is always with you."]}}' WHERE id = 'lesson-w3-age-0-4';

UPDATE lessons SET teaching_extra = '{"introduction":"God''s power is real and available to us. We do not face hard things alone — God is our strength.","activity_note":"See activity page.","confession":"I can do all things through Christ who gives me strength.","closing_prayer":"Dear God, thank You that I can do all things through You. Help me to trust Your power. In Jesus'' name, Amen.","think_about_it":"1. When have you needed God''s help to be strong?\n2. What happened when you trusted God?\n3. Who gives you strength?","video_description":"Watch the video and learn how God gives us strength to do hard things."}' WHERE id = 'lesson-w3-age-5-9';

UPDATE lessons SET teaching_extra = '{"introduction":"God''s power is not just for Bible heroes — it is available to you right now. He is an ever-present help in trouble.","activity_note":"See activity page.","confession":"God''s power is greater than anything I face.","closing_prayer":"Lord, I bring my challenges to You. I believe You are greater than anything I face. Fill me with Your strength and courage. In Jesus'' name, Amen.","think_about_it":"1. What situations are hard for you right now?\n2. How can God''s power help you face them?\n3. What does it mean to be strong in the Lord?","video_description":"Watch the video to discover how God gives us the strength to live with courage and faith."}' WHERE id = 'lesson-w3-age-10-12';

UPDATE lessons SET teaching_extra = '{"introduction":"God''s power is made perfect in weakness. When you feel you cannot go on, that is precisely when God''s strength shows up most powerfully.","activity_note":"See activity page.","confession":"I will rely on God''s power, not my own strength.","closing_prayer":"Father, I confess I often try to handle things in my own strength. Teach me to rely on Your power. Let Your strength be made perfect in my weakness. In Jesus'' name, Amen.","think_about_it":"1. In what area of your life do you most need God''s power?\n2. What does it mean to boast in weakness like Paul did?\n3. How can relying on God''s power make you more effective?","video_description":"Watch the video to learn how God''s power enables us to overcome, serve, and make a difference."}' WHERE id = 'lesson-w3-age-13-19';
