name = "kss-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[[d1_databases]]
binding = "DB"
database_name = "kss-db"
database_id = "b95345e1-64cf-48fc-b821-f09676951b0a"

# JWT_SECRET is stored as a Wrangler secret (not here)
